compatibility: "smolbot"
driveTrain:
  subsystem: "driveTrain"
  description: "All motors used in the drive train live here"
  motors:
    groups:
      - "motors"
    rightMotor:
      channel: 30
      type: "CANTalonFX"
      inverted: False
    rightFollower:
      channel: 31
      type: "CANTalonFXFollower"
      inverted: False
    leftMotor:
      channel: 20
      type: "CANTalonFX"
      inverted: False
    leftFollower:
      channel: 21
      type: "CANTalonFXFollower"
      inverted: False
